version: '3'
services:
  next:
    build:
      context: ./next
      dockerfile: Dockerfile
    restart: always
    container_name: next
    expose:
      - 3000

  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    restart: always
    container_name: react
    expose:
      - 80

  nginx-proxy:
    build:
      context: ./nginx
    restart: always
    ports:
      - '3000:3000'
      - '5000:5000'
    links:
      - next
      - react
    container_name: nginx-proxy
    depends_on:
      - react
      - next
